version: '3.8'

services:
  lazybiz:
    build:
      context: .
      dockerfile: Dockerfile
    image: deadmousefuneral009/lazybiz:latest
    container_name: lazybiz_app
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    env_file:
      - backend/.env
    restart: unless-stopped
